### ISSUE TITLE
缺少两个文件夹怎么玩！

### ISSUE THREAD

**Issue by WEI9899** [textGamex/LyricsTools#1]

**Comment by textGamex** [comment]
缺少什么文件夹？好久之前写的了，记不清细节了

**Comment by WEI9899** [comment]
***@***.***
这不是缺少是什么？

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2024年9月28日 08:33
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [textGamex/LyricsTools] 缺少两个文件夹怎么玩！ (Issue #1)


缺少什么文件夹？

―

**Comment by WEI9899** [comment]
还想配个图标好看点，文件都不全！！！！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2024年9月28日 08:33
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [textGamex/LyricsTools] 缺少两个文件夹怎么玩！ (Issue #1)


缺少什么文件夹？

―
